name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-online:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies and build online version
        run: |
          npm ci
          npm run rebuild-db-online
          npm run webpack
          npm run bundle
        env:
          CI: true
          REMOTE_MEDIA_PATH: ${{ secrets.REMOTE_MEDIA_PATH }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: bundle
          clean: true

  build-and-save-offline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies and build offline version
        run: |
          npm ci
          npm run rebuild-db-offline
          npm run webpack
          npm run bundle
          mkdir bundle-offline
          mv bundle bundle-offline/LingView
        env:
          CI: true
          REMOTE_MEDIA_PATH: ${{ secrets.REMOTE_MEDIA_PATH }}

      - name: Upload offline version as artifact
        uses: actions/upload-artifact@v4
        with:
          name: LingView-local
          path: bundle-offline

      - name: Message
        run: echo "Saved offline-compatible local version of LingView as an artifact!"
